#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o noclobber
set -o nounset

# set -o xtrace

source set-environment-variables.sh 

#######################################

# https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-linux

# https://stackoverflow.com/a/43476575/6674256
# need to export PYTHONPATH since it is not already in the environment: 
# `printenv | grep -w PYTHONPATH` returns zero output
export PYTHONPATH="${CONSTRAINT_TOOLS}/utilities"

# no need to export PATH since it is already in the environment: 
# `printenv | grep -w PATH` returns non-zero output 
PATH="${CONSTRAINT_TOOLS}/bin:$PATH" 

#######################################

tool="${1}"
info "Tool: " "${tool}"
shift
args="${@}"
info "Tool arguments: " "${args}"

case "${tool}" in 
  train-germline-model ) 
    PATH="${CONSTRAINT_TOOLS}/train/germline-model:$PATH" 
    train-map-reduce ${args}
    ;;
  train-germline-model-Nonly ) 
    PATH="${CONSTRAINT_TOOLS}/train-Nonly/germline-model:$PATH" 
    train-map-reduce ${args}
    ;;
  browse-germline-model ) 
    PYTHONPATH="${CONSTRAINT_TOOLS}/predict-constraint/germline-model:${PYTHONPATH}"
    PATH="${CONSTRAINT_TOOLS}/flask-app/germline-model:${PATH}"
    flask-app ${args} 
    ;;
  predict-germline-model ) 
    PYTHONPATH="${CONSTRAINT_TOOLS}/predict-constraint/germline-model:${PYTHONPATH}"
    PATH="${CONSTRAINT_TOOLS}/predict-constraint/germline-model:${PATH}"
    predict-map-reduce ${args} 
    ;; 
  predict-germline-model-Nonly ) 
    PYTHONPATH="${CONSTRAINT_TOOLS}/predict-constraint-Nonly/germline-model:${PYTHONPATH}"
    PATH="${CONSTRAINT_TOOLS}/predict-constraint-Nonly/germline-model:${PATH}"
    predict-map-reduce ${args} 
    ;; 
  * )
    error "invalid tool: " "${tool}"
    exit 1
    ;; 
esac 
