#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o noclobber
set -o nounset

# set -o xtrace

source set-environment-variables.sh 

#######################################

# https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-linux

# https://stackoverflow.com/a/43476575/6674256
# need to export PYTHONPATH since it is not already in the environment: 
# `printenv | grep -w PYTHONPATH` returns zero output
export PYTHONPATH="${CONSTRAINT_TOOLS}/utilities:${CONSTRAINT_TOOLS}/predict-constraint"

# no need to export PATH since it is already in the environment: 
# `printenv | grep -w PATH` returns non-zero output 
PATH="${CONSTRAINT_TOOLS}/bin:$PATH" 

#######################################

tool="${1}"
info "\nTool: " "${tool}\n"
shift
args="${@}"
info "Tool arguments: " "${args}\n"

if [[ ${tool} == "train-germline-model" ]]; then 
  PATH="${CONSTRAINT_TOOLS}/train/germline-model:$PATH" 
  train-map-reduce ${args}
elif [[ ${tool} == "dashboard-germline-model" ]]; then 
  PATH="${CONSTRAINT_TOOLS}/flask-app:${PATH}"
  flask-app ${args} 
else
  error "invalid tool: " "${tool}"
  exit 1
fi 
