#!/usr/bin/env bash

neutral_regions="${CONSTRAINT_TOOLS}/$(read-config trainGermlineModel neutralRegions)"
window_size="$(read-config trainGermlineModel windowSize)"

# https://devhints.io/bash#miscellaneous
# put option-fetching before "set -o nounset" so that we can detect flags without arguments
while [[ "$1" =~ ^- ]]; do 
  case $1 in
    --genome ) shift; [[ ! $1 =~ ^- ]] && genome=$1;;
    --mutations ) shift; [[ ! $1 =~ ^- ]] && mutations=$1;;
    --number-chromosomes-min ) shift; [[ ! $1 =~ ^- ]] && number_chromosomes_min=$1;;
    --neutral-regions ) shift; [[ ! $1 =~ ^- ]] && neutral_regions=$1;;
    --window-size ) shift; [[ ! $1 =~ ^- ]] && window_size=$1;;
    --kmer-size ) shift; [[ ! $1 =~ ^- ]] && kmer_size=$1;;
    --output ) shift; [[ ! $1 =~ ^- ]] && output=$1;;
    *) error "$0: " "$1 is an invalid flag"; exit 1;;
  esac 
  shift
done

info "Training on neutral regions: " "${neutral_regions}\n"
info "Size of window used to compute singleton number: " "${window_size}"

set -o errexit
set -o pipefail
# set -o noclobber
set -o nounset
# set -o xtrace

info "$(echo \
  "Remove neutral regions less than ${window_size}bp in length" \
  "(since we cannot use them to compute expected singleton counts for test regions of size ${window_size}bp)" 
)"
info "$(echo \
  "Remove neutral regions on chromosomes X and Y" \
  "(since it is too much trouble to compute allele frequencies there)" 
)"
neutral_regions_filtered="${output}/neutral-regions.filtered.bed"
zcat ${neutral_regions} \
  | awk --assign window_size=${window_size} '$3 - $2 > window_size' \
  | get-nonXY-chromosomes \
  > ${neutral_regions_filtered}

number_of_jobs="2"
info "Number of slurm jobs (tasks): " "${number_of_jobs}"
number_of_neutral_regions=$(wc -l < ${neutral_regions_filtered})
info "Number of (filtered) neutral regions: " "${number_of_neutral_regions}"

number_of_neutral_regions_per_job=$((number_of_neutral_regions / number_of_jobs))
info "Number of neutral regions per job (task): " "${number_of_neutral_regions_per_job}"
number_of_neutral_regions_left_over=$((number_of_neutral_regions % number_of_jobs))
if (( number_of_neutral_regions_left_over > 0 )); then
  info "Number of neutral regions not used in training: " "${number_of_neutral_regions_left_over}"
fi

# each slurm task will store its output files in this temporary directory: 
tmpdir=$(mktemp --tmpdir=${output} --directory)
clean_up () {
  local exit_code="$1"
  if [[ "${exit_code}" == "0" ]]; then 
    info "Deleting tmp directory: " "${tmpdir}"
    rm --recursive --force "${tmpdir}"
  else 
    info "Received exit code ${exit_code}.."
    info "Not deleting tmp directory: " "${tmpdir}"
  fi 
}
# http://redsymbol.net/articles/bash-exit-traps/
# https://medium.com/@dirk.avery/the-bash-trap-trap-ce6083f36700
trap 'clean_up $?' EXIT

info "Submitting slurm job array..."

mkdir --parents ${output}/logs 

# sbatch man-page: 
# A maximum number of simultaneously running tasks from the job array may be
# specified using a "%" separator.  
# For example "--array=0-15%4" will limit the number of simultaneously running
# tasks from this job array to 4.
# We "wait" to ensure that all the jobs/tasks are finished before merging their results
sbatch \
  --wait \
  --array [1-${number_of_jobs}]%250 \
  --job-name "count-on-regions" \
  --output ${output}/logs/count-on-regions.job-%A.task-%a.log \
  count-on-regions \
    --genome ${genome} \
    --mutations ${mutations} \
    --number-chromosomes-min ${number_chromosomes_min} \
    --kmer-size ${kmer_size} \
    --neutral-regions ${neutral_regions_filtered} \
    --tmpdir ${tmpdir} \
    --number-of-neutral-regions-per-job ${number_of_neutral_regions_per_job} \
    --window-size ${window_size}

exit 1 

# TODO: slurp up the 500 json files (make sure that 500 were created), 
#       aggregating the count data from each, 
#       and write a final json containing the final model
#       c.f. calculate_mutation_probabilities










