#!/usr/bin/env bash

# https://devhints.io/bash#miscellaneous
# put option-fetching before "set -o nounset" so that we can detect flags without arguments
while [[ "$1" =~ ^- ]]; do 
  case $1 in
    --header ) shift; [[ ! $1 =~ ^- ]] && header=$1;;
    --regions ) shift; [[ ! $1 =~ ^- ]] && regions=$1;;
    --number-of-jobs ) shift; [[ ! $1 =~ ^- ]] && number_of_jobs=$1;;
    *) error "$0: " "$1 is an invalid flag"; exit 1;;
  esac 
  shift
done

set -o errexit
set -o pipefail
# set -o noclobber
set -o nounset
# set -o xtrace

info "${header}"

number_of_regions=$(wc -l < ${regions})
info "\tNumber of regions:" "${number_of_regions}"

if (( number_of_regions <= number_of_jobs )); then
  error "\tNumber of regions (${number_of_regions}) should be larger than number of jobs (${number_of_jobs})!"
  exit 1 
else
  number_of_regions_per_job=$((number_of_regions / number_of_jobs))
  info "\tNumber of regions per job (task): " "${number_of_regions_per_job}"
fi

number_of_regions_left_over=$((number_of_regions % number_of_jobs))
if (( number_of_regions_left_over > 0 )); then
  info "\tNumber of regions not used in training:" "${number_of_regions_left_over}"
fi

echo ${number_of_regions_per_job}