#!/usr/bin/env python

import sys 

def main():
  left_telomeres = {}
  right_telomeres = {}

  for line in sys.stdin: 
    chromosome, start, end = line.strip().split()
    start = int(start)
    end = int(end)
    if chromosome not in left_telomeres:
      left_telomeres[chromosome] = {'start': start, 'end': end}
    if chromosome not in right_telomeres:
      right_telomeres[chromosome] = {'start': start, 'end': end}
    if start < left_telomeres[chromosome]['start']:
      left_telomeres[chromosome]['start'] = start
      left_telomeres[chromosome]['end'] = end
    if start > right_telomeres[chromosome]['start']:
      right_telomeres[chromosome]['start'] = start
      right_telomeres[chromosome]['end'] = end

  nonXY_chromosomes = {f'chr{i}' for i in range(1,23)}
  for chromosome in nonXY_chromosomes:
    # left telomere
    start = left_telomeres[chromosome]['start']
    end = left_telomeres[chromosome]['end']
    print(f"{chromosome}\t{start}\t{end}")
    # right telomere
    start = right_telomeres[chromosome]['start']
    end = right_telomeres[chromosome]['end']
    print(f"{chromosome}\t{start}\t{end}")

if __name__ == '__main__': 
  main()
  
