#!/usr/bin/env python

import sys 
import pandas as pd 

def main(): 
  gene_symbols = pd.read_csv(sys.argv[1], sep='\t', header=None)
  gene_symbols.columns = ['gene_symbol']

  exon_coordinates_and_gene_symbols = pd.read_csv(sys.argv[2], sep='\t', header=None)
  # download-process-data/canonical-exons-grch38.sql
  exon_coordinates_and_gene_symbols.columns = ['chromosome', 'exon_start', 'exon_end', 'gene_symbol', 'exon_rank', 'strand', 'exon_is_constitutive', 'gene_biotype']

  subset_exon_coordinates_and_gene_symbols = pd.merge(
    gene_symbols, 
    exon_coordinates_and_gene_symbols, 
    on='gene_symbol', 
    how='inner'
  )

  subset_exon_coordinates_and_gene_symbols = subset_exon_coordinates_and_gene_symbols[
    ['chromosome', 'exon_start', 'exon_end', 'gene_symbol', 'exon_rank', 'gene_biotype']
  ]

  subset_exon_coordinates_and_gene_symbols.to_csv(
    sys.stdout, 
    sep='\t', 
    index=False, 
    header=False
  )

if __name__ == "__main__": 
  main()