#!/usr/bin/env python

import sys 
import color_traceback

def main():
  nonXY_chromosomes = {f'chr{i}' for i in range(1,23)}
  
  for line in sys.stdin: 
    chromosome = line.strip().split()[0]
    if chromosome in nonXY_chromosomes: 
      print(line, end='') 

if __name__ == '__main__': 
  main()