#!/usr/bin/env python

import sys 
import color_traceback

def main():
  regular_chromosomes = set(str(id) for id in list(range(1,23)) + ['X', 'Y'])
  
  for line in sys.stdin: 
    chromosome = line.strip().split()[0].strip('chr')
    if chromosome in regular_chromosomes: 
      print(line, end="") 

if __name__ == '__main__': 
  main()