#!/usr/bin/env python

import sys 
import pandas as pd 

def main(): 
  critical_genes = pd.read_csv(sys.argv[1], sep='\t', header=None)
  critical_gene_symbols = set(critical_genes.iloc[:, 3])

  genes = pd.read_csv(sys.argv[2], sep='\t', header=None)
  for _, row in genes.iterrows(): 
    chrom, start, end, symbol = row     
    if symbol not in critical_gene_symbols: 
      print(f'{chrom}\t{start}\t{end}\t{symbol}')

if __name__ == "__main__": 
  main()