#!/usr/bin/env python3

import os
import pandas as pd

gBGC_path = os.getenv('gBGC_path')
pop = os.getenv('pop')

columns = f"chromosome,start,end,B_M1star.{pop},Bmean_M3starPop.{pop},Bmean_M3starHM.{pop},Bmean_M3starHMT6.{pop}"
columns = columns.strip().split(',')

df = pd.read_csv(f'{gBGC_path}/gBGC-coefficient.hg18.{pop}.tsv', sep='\t')
df = df[columns]
df = df.fillna('.')
df.to_csv(f'{gBGC_path}/gBGC-coefficient.hg18.{pop}.bed', sep='\t', header=False, index=False)

# Write the columns to disk
with open(f'{gBGC_path}/gBGC-coefficient.{pop}.columns.txt', 'w') as f:
  for column in columns:
    f.write(column + '\n')