#!/usr/bin/env python3

import os

GBGC_PATH = os.getenv('GBGC_PATH')
POP = os.getenv('POP')

with open(f'{GBGC_PATH}/gBGC-coefficient.{POP}.columns.txt', 'r') as f:
    lines = f.read().splitlines()
print('\t'.join(lines))