#!/usr/bin/env bash

set -o errexit
# set -o xtrace 

echo $(jq \
        --raw-output \
        --arg key1 $1 \
        --arg key2 $2 \
        '.[$key1][$key2]' \
        ${CONSTRAINT_TOOLS}/.config.json)
