#!/usr/bin/env python
import argparse
import sys 

def parse_arguments():
    parser = argparse.ArgumentParser(description='')

    parser.add_argument('--train', type=str)
    parser.add_argument('--test', type=str)

    return parser.parse_args()

def split_trustworthy_noncoding_regions(): 
  chromosomes_train = ( 
    [f'chr{i}' for i in [2, 4, 6, 8]] + 
    [f'chr{i}' for i in range(10,23)]
  )

  args = parse_arguments()
  
  with (
    open(args.train, 'w') as regions_train, 
    open(args.test, 'w') as regions_test
  ): 
    for region in sys.stdin: 
      chromosome = region.split('\t')[0]
      if chromosome in chromosomes_train: 
        regions_train.write(region)
      else: 
        regions_test.write(region)

if __name__ == '__main__': 
  split_trustworthy_noncoding_regions()
