#!/usr/bin/env bash

# https://devhints.io/bash#miscellaneous
# put option-fetching before "set -o nounset" so that we can detect flags without arguments
while [[ "$1" =~ ^- ]]; do
  case $1 in
    --chromosome ) shift; [[ ! $1 =~ ^- ]] && chromosome=$1;;
    --number-of-intervals-per-job ) shift; [[ ! $1 =~ ^- ]] && number_of_intervals_per_job=$1;;
    --number-of-jobs ) shift; [[ ! $1 =~ ^- ]] && number_of_jobs=$1;;
    --number-of-intervals-per-chromosome ) shift; [[ ! $1 =~ ^- ]] && number_of_intervals_per_chromosome=$1;;
    *) error "$0: $1 is an invalid flag"; exit 1;;
  esac
  shift
done

set -o errexit
set -o pipefail
# set -o noclobber
set -o xtrace
set -o nounset 

#######################################

info "extract vep labels from vcf for ${chromosome} ..."

variants_directory="${CONSTRAINT_TOOLS_DATA}/gnomad/v3/variants" 
variants="${variants_directory}/gnomad_v3_${chromosome}"
vep_keys="${variants_directory}/gnomad_v3_${chromosome}.vep-keys.txt"

bcftools view -h ${variants}.vcf.gz \
  | grep "ID=vep" \
  | tr ": " "\n" \
  | grep -i Allele \
  | sed 's/">//' \
  | tr "|" "\n" \
  > ${vep_keys}

#######################################

info "get intervals for ${chromosome} ..."

intervals="${CONSTRAINT_TOOLS_DATA}/map-reduce-intervals/intervals.bed"
intervals_on_chromosome="${CONSTRAINT_TOOLS_DATA}/map-reduce-intervals/intervals.${chromosome}.bed"

cat ${intervals} \
  | tail -n +2 \
  | grep -w ${chromosome} \
  > ${intervals_on_chromosome}

# sanity check
if [[ ${number_of_intervals_per_chromosome} -ne $(wc -l < ${intervals_on_chromosome}) ]]; then 
  error "number_of_intervals_per_chromosome != $(wc -l < ${intervals_on_chromosome})"
  exit 1 
fi 

#######################################

# info "Submitting slurm job array for ${chromosome} with ${number_of_jobs} jobs (tasks) and ${number_of_intervals_per_job} intervals per job..."

# each slurm task will store its output files in this temporary directory: 
tmpdir=$(mktemp --tmpdir=${variants_directory} --directory)
clean_up () {
  local exit_code="$1"
  if [[ "${exit_code}" == "0" ]]; then 
    info "Deleting tmp directory for ${chromosome}..."
    rm --recursive --force "${tmpdir}"
  else 
    info "Received exit code ${exit_code}.."
    info "Not deleting tmp directory for ${chromosome}..."
  fi 
}
# http://redsymbol.net/articles/bash-exit-traps/
# https://medium.com/@dirk.avery/the-bash-trap-trap-ce6083f36700
trap 'clean_up $?' EXIT

success_signature="TSV FILE READY TO MERGE"

# sbatch man-page: 
# A maximum number of simultaneously running tasks from the job array may be
# specified using a "%" separator.  
# For example "--array=0-15%4" will limit the number of simultaneously running
# tasks from this job array to 4.
# We "wait" for two reasons: 
#   1. to ensure that all the jobs/tasks are finished before merging their results
#   2. because the number of jobs per chromosome is already at the allowable limit for job submissions on slurm
sbatch \
  --wait \
  --array [1-${number_of_jobs}]%250 \
  --job-name "vcf-to-tsv-${chromosome}" \
  --output ${tmpdir}/gnomad_v3_${chromosome}.vcf-to-tsv.job-%A.task-%a.log \
  vcf-to-tsv-intervals \
    --vcf ${variants}.vcf.gz \
    --vep-keys ${vep_keys} \
    --intervals-on-chromosome ${intervals_on_chromosome} \
    --number-of-intervals-per-job ${number_of_intervals_per_job} \
    --tmpdir ${tmpdir} \
    --success-signature "${success_signature}"

#######################################

number_of_log_files=$(ls ${tmpdir}/*.log | wc -l) || true
if [[ ${number_of_log_files} != ${number_of_jobs} ]]; then 
  error "only ${number_of_log_files}/${number_of_jobs} jobs completed successfully"
  error "did not merge..."
  exit 1 
fi 

for log_file in ${tmpdir}/*.log; do 
  number_of_successfully_processed_intervals_per_job=$(grep --count "^${success_signature}" ${log_file}) || true
  if [[ ${number_of_successfully_processed_intervals_per_job} != ${number_of_intervals_per_job} ]]; then 
    error "only ${number_of_successfully_processed_intervals_per_job}/${number_of_intervals_per_job} intervals were completed successfully"
    error "log file: ${log_file}"
    error "did not merge..."
    exit 1
  fi 
done 

info "All jobs to convert ${chromosome} variants from vcf to tsv format were successful..."
info "Merging tsv files, and sorting and block compressing, for ${chromosome}..."

random_tsv_file=$(ls ${tmpdir}/*.tsv | head -1) || true

set +o errexit
(
  head -1 ${random_tsv_file}
  tail -n +2 --quiet ${tmpdir}/*.tsv | sort --version-sort -k1,1 -k2,2n -k3,3n
) |
  bgzip > ${variants}.sorted.tsv.gz
set -o errexit

info "Indexing tsv file for ${chromosome}..."
# http://www.htslib.org/doc/tabix.html
tabix \
    --skip-lines 1 \
    --sequence 1 \
    --begin 2 \
    --end 3 \
    --force \
  ${variants}.sorted.tsv.gz


