#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

jq="${CONSTRAINT_TOOLS}/bin/jq"

if [[ ! -f ${jq}  ]]; then
  wget -O ${jq} https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
  chmod +x ${jq}
else
  info "skipping installation of jq"
fi 

# no need to export PATH since it is already in the environment: 
# `printenv | grep -w PATH` returns non-zero output 
PATH="${CONSTRAINT_TOOLS}/bin:$PATH" 

info "jq version is: $(jq --version)"
