#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

# No need to export PATH since it is already in the environment: 
# `printenv | grep -w PATH` returns non-zero output 
PATH="${CONSTRAINT_TOOLS}/bin:$PATH" 

report_version () { 
  info "bcftools version is:"
  bcftools --version
}

mkdir --parents ${CONSTRAINT_TOOLS}/library
cd ${CONSTRAINT_TOOLS}/library 

version="1.10.2"
tool="bcftools"

if [[ ! -d "${tool}-${version}" ]]; then
  # http://www.htslib.org/download/
  wget https://github.com/samtools/bcftools/releases/download/${version}/${tool}-${version}.tar.bz2
  bzip2 -d ${tool}-${version}.tar.bz2
  tar -xvf ${tool}-${version}.tar
  rm ${tool}-${version}.tar
  cd ${tool}-${version}/
  ./configure --prefix=${CONSTRAINT_TOOLS}
  make
  make install
  report_version
else 
  report_version
  info "skipping installation of ${tool}"
fi 