#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

# No need to export PATH since it is already in the environment: 
# `printenv | grep -w PATH` returns non-zero output 
PATH="${CONSTRAINT_TOOLS}/bin:$PATH" 

report_version () { 
  info "bedtools version is: $(bedtools --version)"
}

mkdir --parents ${CONSTRAINT_TOOLS}/library
cd ${CONSTRAINT_TOOLS}/library 

tool="bedtools2"

if [[ ! -d ${tool} ]]; then 
  git clone https://github.com/arq5x/${tool}.git
  cd ${tool}
  # https://github.com/arq5x/bedtools2/commit/1f067f38c089773e01571380cfdcdaa74a827536
  git checkout 1f067f38c089773e01571380cfdcdaa74a827536
  make
  cp bin/bedtools ${CONSTRAINT_TOOLS}/bin
  report_version
else 
  report_version
  info "skipping installation of ${tool}"
fi 