#!/usr/bin/env bash

# set -o xtrace 

model="${CONSTRAINT_TOOLS}/$(read-config dashboard model)"
region=$(read-config dashboard region)
window_size=$(read-config dashboard windowSize)
window_stride=$(read-config dashboard windowStride)

# https://devhints.io/bash#miscellaneous
# put option-fetching before "set -o nounset" so that we can detect flags without arguments
while [[ "$1" =~ ^- ]]; do 
  case $1 in
    --model ) shift; [[ ! $1 =~ ^- ]] && model=$1;;
    --port ) shift; [[ ! $1 =~ ^- ]] && port=$1;;
    *) error "$0: $1 is an invalid flag"; exit 1;;
  esac 
  shift
done

info "using the model specified at:"
info "${model}\n"

set -o errexit
set -o pipefail
set -o noclobber
set -o nounset

cd ${CONSTRAINT_TOOLS}/flask-app
FLASK_ENV="development" # https://flask.palletsprojects.com/en/2.0.x/server/#in-code
python flask-app.py \
  --model ${model} \
  --port ${port} \
  --region ${region} \
  --window-size ${window_size} \
  --window-stride ${window_stride}


