set -o errexit
set -o pipefail
# set -o noclobber

set -o xtrace
set -o nounset 

source set-environment-variables.sh 

# https://dcc.icgc.org/releases/PCAWG/reference_data/pcawg-bwa-mem
# https://www.cureffi.org/2013/02/01/the-decoy-genome/

reference_url="https://dcc.icgc.org/api/v1/download?fn=/PCAWG/reference_data/pcawg-bwa-mem"
reference_path="${CONSTRAINT_TOOLS}/data/reference/grch37"

mkdir --parents ${reference_path}

download_file_with_suffix () {
  local suffix_=$1
  wget ${reference_url}/genome.${suffix_} --output-document=${reference_path}/genome.${suffix_}  
}

info "Downloading GRCH37 reference plus decoy sequences..."
wget ${reference_url}/README.txt --output-document=${reference_path}/README.txt
download_file_with_suffix "fa.gz"

check_digest () { 
  local suffix_=$1
  local expected_digest_=$2
  observed_digest_=$(md5sum ${reference_path}/genome.${suffix_} | awk '{ print $1 }')
  if [[ ${observed_digest_} == ${expected_digest_} ]]; then 
    info "${reference_path}/genome.${suffix_}: digest check passed" 
  else
    info "${reference_path}/genome.${suffix_}: digest check failed"
  fi 
}

check_digest "fa.gz" "a07c7647c4f2e78977068e9a4a31af15"

info "Decompressing reference file..."
# https://unix.stackexchange.com/a/158538/406037
set +o errexit
gzip --decompress ${reference_path}/genome.fa.gz 
set -o errexit

info "Block compressing reference file..."
bgzip --stdout ${reference_path}/genome.fa > ${reference_path}/genome.fa.gz

info "Indexing block-compressed fasta file...."
samtools faidx ${reference_path}/genome.fa.gz

# the index produced by "samtools faidx" is compatible with pyfaidx: 
# "FASTA index files generated by samtools, the faidx utility, and the pyfaidx module are compatible and interchangeable"
# from: https://peerj.com/preprints/970/
# HOWEVER, I encountered this error when using pyfaidx: 
# https://github.com/mdshw5/pyfaidx/issues/124

# A better option is pysam.FastaFile
# The "samtools faidx" index is also compatible with pysam.FastaFile: 
# https://pysam.readthedocs.io/en/latest/api.html?highlight=fasta#pysam.FastaFile

info "Removing uncompressed fasta file ... "
rm ${reference_path}/genome.fa





