#!/usr/bin/env python

import sys 

def main():
  target_repeat_classes = {'SINE', 'LINE', 'LTR', 'DNA'}
  
  for line in sys.stdin: 
    repeat_class = line.strip().split()[5].strip()
    if repeat_class in target_repeat_classes: 
      print(line, end="") 

if __name__ == '__main__': 
  main()